name: Build Release Packages

# 手动触发工作流
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for release'
        required: true
        default: 'v1.0.0'
        type: string

env:
  FLUTTER_VERSION: '3.24.5'

jobs:
  # macOS构建和DMG打包
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build macOS app
        run: |
          flutter build macos --release

      - name: Create DMG
        run: |
          # 安装 create-dmg 工具
          brew install create-dmg
          
          # 创建DMG文件
          create-dmg \
            --volname "Corgi Recite" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon "Corgi Recite.app" 200 190 \
            --hide-extension "Corgi Recite.app" \
            --app-drop-link 600 185 \
            "Corgi-Recite-${{ github.event.inputs.version }}-macOS.dmg" \
            "build/macos/Build/Products/Release/"

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: corgi-recite-macos-dmg
          path: corgi_recite/Corgi-Recite-${{ github.event.inputs.version }}-macOS.dmg

  # Windows构建和ZIP打包
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build Windows app
        run: |
          flutter build windows --release

      - name: Create ZIP package
        run: |/build/windows/x64/runner/Release
          # 使用PowerShell创建ZIP文件
          Compress-Archive -Path * -DestinationPath "../../../../../Corgi-Recite-${{ github.event.inputs.version }}-Windows.zip"

      - name: Upload Windows ZIP
        uses: actions/upload-artifact@v4
        with:
          name: corgi-recite-windows-zip
          path: corgi_recite/Corgi-Recite-${{ github.event.inputs.version }}-Windows.zip

  # Android APK构建
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build Android APK
        run: |
          flutter build apk --release

      - name: Rename APK
        run: |
          cp build/app/outputs/flutter-apk/app-release.apk "Corgi-Recite-${{ github.event.inputs.version }}-Android.apk"

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: corgi-recite-android-apk
          path: corgi_recite/Corgi-Recite-${{ github.event.inputs.version }}-Android.apk

  # iOS构建和未签名IPA制作
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build iOS app (unsigned)
        run: |
          flutter build ios --release --no-codesign

      - name: Create unsigned IPA
        run: |
          # 创建Payload目录
          mkdir -p Payload
          
          # 复制.app文件到Payload目录
          cp -r build/ios/iphoneos/Runner.app Payload/
          
          # 重命名为Corgi Recite.app
          mv Payload/Runner.app "Payload/Corgi Recite.app"
          
          # 创建IPA文件（实际上是ZIP文件）
          zip -r "Corgi-Recite-${{ github.event.inputs.version }}-iOS-unsigned.ipa" Payload/
          
          # 清理临时文件
          rm -rf Payload/

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: corgi-recite-ios-ipa
          path: corgi_recite/Corgi-Recite-${{ github.event.inputs.version }}-iOS-unsigned.ipa

  # 创建GitHub Release（可选）
  # create-release:
  #   runs-on: ubuntu-latest
  #   needs: [build-macos, build-windows, build-android, build-ios]
  #   if: always() && (needs.build-macos.result == 'success' || needs.build-windows.result == 'success' || needs.build-android.result == 'success' || needs.build-ios.result == 'success')
  #   steps:
  #     - name: Download all artifacts
  #       uses: actions/download-artifact@v4

  #     - name: Create Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         tag_name: ${{ github.event.inputs.version }}
  #         name: Corgi Recite ${{ github.event.inputs.version }}
  #         body: |
  #           ## Corgi Recite ${{ github.event.inputs.version }}
            
  #           ### 下载安装包
            
  #           - **macOS**: `Corgi-Recite-${{ github.event.inputs.version }}-macOS.dmg` - macOS安装包
  #           - **Windows**: `Corgi-Recite-${{ github.event.inputs.version }}-Windows.zip` - Windows便携版
  #           - **Android**: `Corgi-Recite-${{ github.event.inputs.version }}-Android.apk` - Android安装包
  #           - **iOS**: `Corgi-Recite-${{ github.event.inputs.version }}-iOS-unsigned.ipa` - iOS未签名安装包（需要开发者证书或越狱设备）
            
  #           ### 功能特性
  #           - 智能词语背诵和测试
  #           - 支持填空式默写（介词、不定代词、词性标注）
  #           - 多对多词语关系管理
  #           - 数据导入导出功能
  #           - 跨平台支持
            
  #           ### 安装说明
  #           - **macOS**: 下载DMG文件，双击安装
  #           - **Windows**: 下载ZIP文件，解压后运行corgi_recite.exe
  #           - **Android**: 下载APK文件，允许安装未知来源应用后安装
  #           - **iOS**: 需要开发者证书签名或在越狱设备上安装
  #         files: |
  #           corgi-recite-macos-dmg/*
  #           corgi-recite-windows-zip/*
  #           corgi-recite-android-apk/*
  #           corgi-recite-ios-ipa/*
  #         draft: false
  #         prerelease: false